{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "fax-ui.fullname" . }}
  labels:
    {{- include "fax-ui.labels" . | nindent 4 }}
spec:
  {{- with .Values.gateway.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  parentRefs:
    {{- range .Values.gateway.parentRefs }}
    - name: {{ .name | quote }}
      {{- if .namespace }}
      namespace: {{ .namespace | quote }}
      {{- end }}
    {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.gateway.path | default "/" | quote }}
      backendRefs:
        - name: {{ include "fax-ui.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
