{{- if and (not .Values.existingTelnyxSecret.name) .Values.telnyx.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fax-ui.fullname" . }}-telnyx
  labels:
    {{- include "fax-ui.labels" . | nindent 4 }}
type: Opaque
data:
  TELNYX_API_KEY: {{ .Values.telnyx.apiKey | b64enc | quote }}
{{- end }}
