{{- if .Values.envSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fax-ui.fullname" . }}-env
  labels:
    {{- include "fax-ui.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $hipaa := (ternary "true" "false" .Values.env.hipaaMode) -}}
  HIPAA_MODE: {{ $hipaa | b64enc | quote }}
  PUBLIC_BASE_URL: {{ (.Values.env.publicBaseURL | default "") | b64enc | quote }}
  FAX_CONNECTION_ID: {{ (.Values.env.connectionID | default "") | b64enc | quote }}
  FAX_FROM_DEFAULT: {{ (.Values.env.fromNumber | default "") | b64enc | quote }}
  {{- $inMem := (ternary "true" "false" .Values.env.uploadsInMemory) -}}
  UPLOAD_IN_MEMORY: {{ $inMem | b64enc | quote }}
{{- end }}
