{{- if and .Values.ngrok.enabled (not .Values.ngrok.existingSecret.name) .Values.ngrok.authtoken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fax-ui.fullname" . }}-ngrok
  labels:
    {{- include "fax-ui.labels" . | nindent 4 }}
type: Opaque
data:
  NGROK_AUTHTOKEN: {{ .Values.ngrok.authtoken | b64enc | quote }}
{{- end }}
